version: "3"

services:
    contacts-api:
        container_name: contacts-api
        image: ja-boop/contacts-api:1.0.0
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
    db:
        container_name: mysql-db
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./data/mysql/:/var/lib/mysql
